// Fill __RUN__, __ORIGIN__, __DEST__ into a new file. Real clicks/drags only. Performance version must be frozen.
async page => {
const runName='__RUN__',origin=__ORIGIN__,destination=__DEST__;
const root='_dev/shots/audio/round3/'+runName+'/';
const log=[],consoleErrors=[],loadedSources=[],lookChecks=[],scanCoverage=[],runnerErrors=[];let n=0,lastShot=0,lastLook=0,lastKey='',done=false,seatDone=false;
page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('pageerror',e=>consoleErrors.push(String(e)));
await page.setViewportSize({width:1112,height:834});const cdp=await page.context().newCDPSession(page);if(await page.evaluate(()=>devicePixelRatio)!==2)throw Error('Open this session with _dev/tools/audio/playwright-ipad.json: native context DPR2 required');await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await cdp.send('Emulation.setCPUThrottlingRate',{rate:6});const scriptResponses=[];cdp.on('Network.responseReceived',e=>{if(/(?:\/js\/metro\/[^?]+\.js|\/css\/metro\.css|\/metro\.html)(?:\?|$)/.test(e.response.url))scriptResponses.push({requestId:e.requestId,url:e.response.url,status:e.response.status});});
const loadStarted=Date.now();
await page.goto('http://localhost:8080/metro.html?perf=1&qa='+runName+'-'+Date.now());
await page.waitForFunction(()=>window.GZ?.debug?.state().stage==='selection',undefined,{timeout:60000});
const loadingMilliseconds=Date.now()-loadStarted;
const gpuInfo=await page.evaluate(()=>{const c=document.getElementById('scene'),g=c.getContext('webgl2')||c.getContext('webgl'),ext=g?.getExtension('WEBGL_debug_renderer_info');return g?{vendor:g.getParameter(g.VENDOR),renderer:g.getParameter(g.RENDERER),unmaskedVendor:ext?g.getParameter(ext.UNMASKED_VENDOR_WEBGL):null,unmaskedRenderer:ext?g.getParameter(ext.UNMASKED_RENDERER_WEBGL):null,attributes:g.getContextAttributes(),devicePixelRatio}:null;});
const actualUrls=await page.evaluate(()=>[location.href,...document.scripts].map(x=>typeof x==='string'?x:x.src).concat([...document.querySelectorAll('link[rel="stylesheet"]')].map(x=>x.href)));for(const response of scriptResponses.filter(r=>actualUrls.includes(r.url))){try{const body=await cdp.send('Network.getResponseBody',{requestId:response.requestId});const digest=await page.evaluate(async source=>{const bytes=new TextEncoder().encode(source);return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');},body.body);loadedSources.push({url:response.url,status:response.status,sha256:digest,characters:body.body.length,base64Encoded:body.base64Encoded});}catch(e){loadedSources.push({url:response.url,error:String(e)});}}
await page.evaluate(()=>{
 window.audioQA={start:performance.now(),timeOrigin:performance.timeOrigin,events:[{at:performance.now(),name:'qa-cpu-throttle',rate:6}],trace:[],frameWindows:[],captureActive:false,ended:false,initialPressure:{devicePixelRatio,rendererPixelRatio:GZ.debug.state().pixelRatio},shadowMapEnabled:GZ.debug.world().renderer.shadowMap.enabled,initialPhysics:{...GZ.debug.world().crowd.physicsStats},exactGeometryPresent:!!GZ.debug.world().geometry};
 audioQA.exactGeometryCalls={};for(const method of ['sync','nearest','raycast','ground','support','sole']){const proto=GZ.PlayPhysics.Geometry.prototype,original=proto[method];audioQA.exactGeometryCalls[method]=0;proto[method]=function(...args){audioQA.exactGeometryCalls[method]++;return original.apply(this,args);};}
 audioQA.auditUpdateCalls=0;const qaAuditOriginal=GZ.PlayPhysics.Audit.prototype.update;GZ.PlayPhysics.Audit.prototype.update=function(...args){audioQA.auditUpdateCalls++;return qaAuditOriginal.apply(this,args);};
 audioQA.worldValidationCalls=0;const qaValidateOriginal=GZ.Station.validate;GZ.Station.validate=function(...args){audioQA.worldValidationCalls++;return qaValidateOriginal.apply(this,args);};
 audioQA.legacyPhysicsCalls={};for(const method of ['resolve','fitFeet','fitActor']){const crowd=GZ.debug.world().crowd,original=crowd[method];audioQA.legacyPhysicsCalls[method]=0;crowd[method]=function(...args){audioQA.legacyPhysicsCalls[method]++;return original.apply(this,args);};}
 const qaCrowd=GZ.debug.world().crowd,qaRelocate=qaCrowd.relocateFast;qaCrowd.relocateFast=function(actor){const before={x:actor.position.x,y:actor.position.y,z:actor.position.z},result=qaRelocate.call(this,actor);if(!result)audioQA.events.push({at:performance.now(),name:'qa-relocation-failed',id:actor.id,state:actor.state,pose:actor.pose,position:before,stage:GZ.debug.state().stage,current:GZ.debug.state().current});return result;};
 let rafLast=performance.now(),windowSeconds=0,windowFrames=0,windowWorst=0,windowCaptured=false,windowStage=GZ.debug.state().stage;
 function observeFrames(t){const dt=(t-rafLast)/1000;rafLast=t;if(dt>0){windowSeconds+=dt;windowFrames++;windowWorst=Math.max(windowWorst,dt*1000);windowCaptured=windowCaptured||audioQA.captureActive;}if(windowSeconds>=1){audioQA.frameWindows.push({at:t,stage:windowStage,seconds:windowSeconds,frames:windowFrames,fps:windowFrames/windowSeconds,intervalWorst:windowWorst,containsQACapture:windowCaptured,devicePixelRatio,rendererPixelRatio:GZ.debug.state().pixelRatio});windowSeconds=0;windowFrames=0;windowWorst=0;windowCaptured=false;windowStage=GZ.debug.state().stage;}if(!audioQA.ended)requestAnimationFrame(observeFrames);}requestAnimationFrame(observeFrames);
 document.addEventListener('click',e=>audioQA.events.push({at:performance.now(),name:'real-click',target:e.target.id||e.target.closest('button')?.id||e.target.tagName,text:e.target.textContent?.slice(0,80),stage:GZ.debug.state().stage}),true);
 ['sfx','announce','trainApproach'].forEach(name=>{const original=GZ.Audio[name];GZ.Audio[name]=function(...args){const st=GZ.debug.state(),w=GZ.debug.world();let doorGeometry=null;if(name==='sfx'&&/^(door|psd)(Open|Close)$/.test(args[0])){const td=w.train;const point=side=>{const d=td.doors.find(d=>d.side===side&&Math.abs(d.x-st.door.x)<.1);if(!d)return null;const p=td.group.localToWorld(new THREE.Vector3(d.x,d.y,d.z));return {x:p.x,y:p.y,z:p.z};};doorGeometry={boarding:point(st.door.side),alight:point(st.alightSide),starts:{boarding:st.doors,alight:st.alightDoors},spanish:st.spanishLayout,current:st.current,dir:st.dir};}const r=original.apply(this,args);const panners=doorGeometry?GZ.Audio.getState().spatialSources.filter(p=>p.id==='sfx.'+args[0]||p.id===args[0]):null;if(name!=='sfx'||!/footstep/.test(args[0]))audioQA.events.push({at:performance.now(),name,args,result:typeof r==='number'?r:null,stage:GZ.debug.state().stage,doorGeometry,panners});return r;};});
 window.addEventListener('gz-audio-caption',e=>audioQA.events.push({at:performance.now(),name:'caption',detail:e.detail}));
 function sample(){const s=GZ.debug.state(),crowd=GZ.debug.world().crowd;audioQA.trace.push({devicePixelRatio,physics:{...crowd.physicsStats},crowdLimit:crowd.limit,secondaryAnimations:crowd.secondaryAnimations,at:performance.now(),fps:s.fps,stage:s.stage,current:s.current,moving:s.moving,p:s.position,cam:s.camera,doors:s.doors,alight:s.alightDoors,anim:s.doorAnimating,speed:s.speed,seated:s.seated,audio:{zone:s.audio.zone,speed:s.audio.speed,inside:s.audio.inside,announcing:s.audio.announcing,active:s.audio.active,errors:s.audio.errors},auditAvailable:!!GZ.debug.audit,auditEnabled:s.auditEnabled,perf:s.perf,drawCalls:s.drawCalls,triangles:s.triangles,pixelRatio:s.pixelRatio,audioResources:{decodedBytes:s.audio.decodedBytes,voiceCacheBytes:s.audio.voiceCacheBytes,spatialPannerCount:s.audio.spatialPannerCount,hrtfPannerCount:s.audio.hrtfPannerCount}});if(!audioQA.ended)setTimeout(sample,150);} sample();
});
const state=()=>page.evaluate(()=>{const s=GZ.debug.state();return {...s,audio:{zone:s.audio.zone,speed:s.audio.speed,inside:s.audio.inside,context:s.audio.context,announcing:s.audio.announcing,stationAnnouncing:s.audio.stationAnnouncing,errors:s.audio.errors},buttons:[...document.querySelectorAll('button')].filter(b=>b.offsetParent&&!b.disabled).map(b=>({id:b.id,text:b.textContent.trim()}))};});
const captureMachine=()=>page.evaluate(()=>{const target=document.getElementById('interactionTarget');if(!target||!target.offsetParent)return null;const r=target.getBoundingClientRect(),cam=GZ.debug.camera(),w=GZ.debug.world();const caster=new THREE.Raycaster();caster.setFromCamera(new THREE.Vector2((r.x+r.width/2)/innerWidth*2-1,1-(r.y+r.height/2)/innerHeight*2),cam);const hits=caster.intersectObjects(w.scene.children,true).filter(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent;}const m=h.object.material;return Array.isArray(m)||!m||m.opacity>.8;});return {at:performance.now(),stage:GZ.debug.state().stage,interaction:GZ.debug.state().interaction,viewport:{width:innerWidth,height:innerHeight},rect:{x:r.x,y:r.y,width:r.width,height:r.height},hitTarget:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.id,first:hits.slice(0,3).map(h=>({name:h.object.name,type:h.object.type,distance:h.distance,instanceId:h.instanceId,npc:w.crowd.parts.some(p=>p.mesh===h.object)}))};});
const machineVisibility=[];
const snap=async(tag)=>{await page.evaluate(tag=>{audioQA.captureActive=true;audioQA.events.push({at:performance.now(),name:'qa-screenshot-start',tag});},tag);const filename=String(++n).padStart(4,'0')+'-'+tag.replace(/[^a-zA-Z0-9_-]/g,'-')+'.png';await page.screenshot({path:root+filename});log.push({filename,state:await state()});const visible=await captureMachine();if(visible)machineVisibility.push({filename,...visible});await page.evaluate(filename=>{audioQA.events.push({at:performance.now(),name:'qa-screenshot-end',filename});audioQA.captureActive=false;},filename);lastShot=Date.now();};
const drag=async(dx,dy)=>{if(Math.abs(dx)+Math.abs(dy)<9)return;const vp=page.viewportSize();const steps=Math.max(1,Math.ceil(Math.max(Math.abs(dx)/(vp.width*.62),Math.abs(dy)/(vp.height*.25))));for(let i=0;i<steps;i++){const ddx=dx/steps,ddy=dy/steps;const start=await page.evaluate(({dx,dy,w,h})=>{for(const y of [h*.40,h*.31,h*.49])for(const x of [dx>=0?w*.13:w*.87,dx>=0?w*.23:w*.77,w*.5]){if(x+dx<8||x+dx>w-8||y+dy<95||y+dy>h-120)continue;if(document.elementFromPoint(x,y)?.id==='scene')return {x,y};}return null;},{dx:ddx,dy:ddy,w:vp.width,h:vp.height});if(!start)throw Error('QA cannot find canvas drag origin');await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(start.x+ddx,start.y+ddy,{steps:8});await page.mouse.up();}};
const look=async(yaw,pitch)=>{for(let attempt=0;attempt<3;attempt++){const s=await state();const dyaw=Math.atan2(Math.sin(yaw-s.camera.yaw),Math.cos(yaw-s.camera.yaw));if(Math.abs(dyaw)<.02&&Math.abs(pitch-s.camera.pitch)<.02)break;await drag(-dyaw/.004,-(pitch-s.camera.pitch)/.003);await page.waitForTimeout(150);}const actual=await state(),yawError=Math.abs(Math.atan2(Math.sin(yaw-actual.camera.yaw),Math.cos(yaw-actual.camera.yaw))),pitchError=Math.abs(pitch-actual.camera.pitch);lookChecks.push({stage:actual.stage,current:actual.current,target:{yaw,pitch},actual:actual.camera,yawError,pitchError});if(yawError>.08||pitchError>.08){await snap('QA-LOOK-NOT-ACHIEVED-'+actual.stage);throw Error('Real drag failed to reach requested view '+JSON.stringify(lookChecks[lookChecks.length-1]));}};
const recover=async(s)=>{if(await page.locator('#findInteraction').isVisible()){await snap('target-offscreen-with-recovery-button');await page.locator('#findInteraction').click();await page.waitForTimeout(1700);await snap('target-recovered-by-child-button');return await page.locator('#interactionTarget').isVisible();}if(Date.now()-lastShot>2000)await snap('TARGET-HIDDEN-'+s.stage);for(const offset of [0,Math.PI/2,Math.PI,-Math.PI/2]){await look(s.camera.yaw+offset,-.55);if(await page.locator('#interactionTarget').isVisible()){await snap('target-found-by-real-sweep');return true;}await look(s.camera.yaw+offset,-.95);if(await page.locator('#interactionTarget').isVisible()){await snap('target-found-by-real-low-sweep');return true;}}return false;};
const scanned=new Set();
const scan=async(tag)=>{const s=await state(),base=s.camera,startLook=lookChecks.length,startShot=n;await snap(tag+'-default');for(let i=1;i<=4;i++){await look(base.yaw+i*Math.PI/2,0);await snap(tag+'-turn'+i);}await look(base.yaw,.65);await snap(tag+'-up');await look(base.yaw,-1.05);await snap(tag+'-down');await look(base.yaw,base.pitch);scanCoverage.push({tag,stage:s.stage,current:s.current,startLook,endLook:lookChecks.length,startShot,endShot:n});};
try{
await page.locator('#stationPicker button[data-col="0"][data-index="'+origin+'"]').click();await page.locator('#stationPicker button[data-col="1"][data-index="'+destination+'"]').click();await snap('selection');await page.locator('#start').click();
const t0=Date.now();let idleSince=Date.now(),lastMotion=Date.now(),motionPos=null,seatAttempts=0,portraitChecks=new Set(),standDone=false,stressActive=false,stressDone=false;
while(Date.now()-t0<1500000){
 const s=await state();if(false&&!stressDone&&s.stage==='closing'){await cdp.send('Emulation.setCPUThrottlingRate',{rate:6});stressActive=true;stressDone=true;await page.evaluate(()=>audioQA.events.push({at:performance.now(),name:'qa-cpu-throttle',rate:6}));}if(stressActive&&s.stage!=='closing'){await cdp.send('Emulation.setCPUThrottlingRate',{rate:6});stressActive=false;await page.evaluate(()=>audioQA.events.push({at:performance.now(),name:'qa-cpu-throttle',rate:6}));}const key=[s.stage,s.current,s.goal,s.interaction,s.coinHeld,s.moving,s.seated].join('|');
 if(key!==lastKey){lastKey=key;idleSince=Date.now();if(s.moving)await snap(s.stage+'-'+s.current+'-walk-start');}
 if(s.stage==='complete'){await snap('complete');await page.waitForTimeout(3000);await snap('complete-stable-after3sec');done=s.current===['gyq','njs','lsly','dsk'][destination]&&s.travelled===Math.abs(destination-origin)&&s.coinHistory.length===4;break;}
 if(s.moving){if(!motionPos||Math.hypot(s.position.x-motionPos.x,s.position.y-motionPos.y,s.position.z-motionPos.z)>.12){motionPos={...s.position};lastMotion=Date.now();}if(Date.now()-lastMotion>35000){await snap('BLOCKED-'+s.stage+'-path'+s.pathIndex);break;}if(Date.now()-lastLook>500){await look(s.camera.yaw+.42,((n%5)-2)*.13);lastLook=Date.now();}if(Date.now()-lastShot>1300)await snap(s.stage+'-'+s.current+'-walk-'+s.pathIndex);await page.waitForTimeout(200);continue;}
 lastMotion=Date.now();motionPos=null;
 const tag=[s.stage,s.current,s.interaction||'',s.goal,s.seated].join('|');
 const transient=['approaching','closing','arriving'].includes(s.stage)||s.doorAnimating;
 if(!s.doorAnimating&&!scanned.has(tag)){scanned.add(tag);await page.waitForTimeout(transient?100:1700);await scan(s.stage+'-'+s.current+'-'+(s.interaction||'idle')+(s.seated?'-seated':''));continue;}
 if(transient){if(Date.now()-lastShot>2000)await snap(s.stage+'-'+s.current+'-t'+Math.round(s.seconds));await page.waitForTimeout(300);continue;}
 if(s.interaction){
  if(runName.includes('portrait')&&['pickup','insert'].includes(s.interaction)&&!portraitChecks.has(s.interaction)){portraitChecks.add(s.interaction);await page.setViewportSize({width:834,height:1112});if(await page.evaluate(()=>devicePixelRatio)!==2)throw Error('Native DPR2 lost after portrait resize');await page.waitForTimeout(700);await look(s.camera.yaw+Math.PI,0);await snap('portrait-'+s.interaction+'-looking-away');const rects=await page.locator('button').evaluateAll(bs=>bs.filter(b=>b.offsetParent).map(b=>{const r=b.getBoundingClientRect();return{id:b.id,text:b.textContent,disabled:b.disabled,x:r.x,y:r.y,w:r.width,h:r.height};}));await page.evaluate(rects=>audioQA.events.push({at:performance.now(),name:'portrait-visible-buttons',rects,scrollWidth:document.documentElement.scrollWidth,innerWidth,devicePixelRatio}),rects);if(await page.locator('#findInteraction').isVisible()){await page.locator('#findInteraction').click();await page.waitForTimeout(1700);await snap('portrait-'+s.interaction+'-recovered');}continue;}
  if(!await page.locator('#interactionTarget').isVisible()&&await page.locator('#findInteraction').isVisible()){await recover(s);continue;}
  if(['pay','brush','insert'].includes(s.interaction)&&!s.coinHeld){await page.locator('#handCoin').click();}
  else if(await page.locator('#interactionTarget').isVisible()){await page.locator('#interactionTarget').click();await page.waitForTimeout(1000);}
  else{if(!await recover(s))throw Error('交互目标不可见 '+JSON.stringify(s));}
 }else if(s.stage==='arrived'&&runName.includes('stand')&&s.seated&&!standDone&&s.buttons.some(b=>b.id==='stand')){standDone=true;await page.locator('#stand').click();await page.waitForTimeout(500);await snap('stand-real-button');
 }else if(s.stage==='arrived'&&s.buttons.some(b=>b.id==='action')){
  if(s.current!==['gyq','njs','lsly','dsk'][destination]){if(s.buttons.some(b=>b.id==='secondary'))await page.locator('#secondary').click();else await page.waitForTimeout(300);}else if(s.buttons.find(b=>b.id==='action')?.text.includes('下车'))await page.locator('#action').click();else await page.waitForTimeout(300);
 }else if(s.trainAttached&&s.stage==='boarding'&&!s.seated&&seatAttempts<3&&s.buttons.some(b=>b.id==='seat')){seatAttempts++;await page.locator('#seat').click();await page.waitForTimeout(1000);await snap('seat-attempt-'+seatAttempts);}
 else if(s.buttons.some(b=>b.id==='action')&&!['riding','waiting','arrived'].includes(s.stage)){await page.locator('#action').click();}
 else{if(Date.now()-lastShot>3500)await snap(s.stage+'-'+s.current+'-hold');await page.waitForTimeout(300);}
 await page.waitForTimeout(350);
}
}catch(e){runnerErrors.push(String(e));try{await snap('QA-FAILED');}catch(captureError){runnerErrors.push(String(captureError));}}
await page.evaluate(()=>audioQA.ended=true);
return {runName,cpuRate:6,loadingMilliseconds,gpuInfo,lookChecks,scanCoverage,runnerErrors,perf:await page.evaluate(()=>GZ.debug.perf?.report?.()||{missing:true}),scope:'Natural CPU6 default production without debug.goto; explicit audit=1 geometry regression is a separate same-version proof. A12 proxy only.',machineVisibility,loadedSources,browserVersion:page.context().browser().version(),done,screenshots:n,log,consoleErrors,final:await state(),qa:await page.evaluate(()=>audioQA),audit:await page.evaluate(()=>GZ.debug.audit?.report?.()||{missing:true}),physics:await page.evaluate(()=>({...GZ.debug.world().crowd.physicsStats})),finishDetail:await page.locator('#finishDetail').textContent(),loadedScripts:await page.evaluate(()=>[...document.scripts].map(s=>s.src))};
}
