/* Play geometry queries. Exact triangle BVHs; no renderer/readback or private World data. */
(function(){'use strict';var GZ=window.GZ=window.GZ||{},T=THREE,cache=new WeakMap(),A=new T.Vector3(),B=new T.Vector3(),C=new T.Vector3(),Q=new T.Vector3(),tri=new T.Triangle(),hit=new T.Vector3(),local=new T.Vector3(),rr=new T.Ray(),worldRay=new T.Ray(),worldHit=new T.Vector3(),inv=new T.Matrix4(),im=new T.Matrix4(),wm=new T.Matrix4(),down=new T.Vector3(0,-1,0),groundOrigin=new T.Vector3();
function tree(g){if(cache.has(g))return cache.get(g);var p=g.attributes.position,ix=g.index,ids=[],bounds=[];for(var t=0;t<(ix?ix.count:p.count)/3;t++){var box=new T.Box3();for(var j=0;j<3;j++){var n=ix?ix.getX(t*3+j):t*3+j;Q.fromBufferAttribute(p,n);box.expandByPoint(Q);}bounds[t]=box;ids.push(t);}function build(ids){var box=new T.Box3();ids.forEach(function(i){box.union(bounds[i]);});var n={box:box};if(ids.length<=12){n.ids=ids;return n;}var s=box.getSize(new T.Vector3()),axis=s.x>s.y&&s.x>s.z?'x':s.y>s.z?'y':'z';ids.sort(function(a,b){return bounds[a].min[axis]+bounds[a].max[axis]-bounds[b].min[axis]-bounds[b].max[axis];});var half=ids.length>>1;n.left=build(ids.slice(0,half));n.right=build(ids.slice(half));return n;}var out={root:build(ids),g:g};cache.set(g,out);return out;}
function triangle(g,id){var p=g.attributes.position,ix=g.index;A.fromBufferAttribute(p,ix?ix.getX(id*3):id*3);B.fromBufferAttribute(p,ix?ix.getX(id*3+1):id*3+1);C.fromBufferAttribute(p,ix?ix.getX(id*3+2):id*3+2);tri.set(A,B,C);}
function visible(o){for(var p=o;p;p=p.parent)if(!p.visible)return false;return true;}
function Geometry(roots,exclude){this.queryCells=new Map();this.largeEntries=new Set();this.records=[];this.exclude=exclude;var self=this;roots.forEach(function(root){root.traverse(function(o){if(!o.isMesh||!o.geometry||o.userData.playBody||o===exclude||exclude&&exclude.children.indexOf(o)>=0)return;var mats=Array.isArray(o.material)?o.material:[o.material];self.records.push({o:o,bvh:tree(o.geometry),opaque:mats.some(function(m){return !m.transparent||m.opacity>=.98;}),matrix:new T.Matrix4(),inverse:new T.Matrix4()});});});this.frame=0;}
Geometry.prototype.indexEntry=function(entry){var b=entry.box,x0=Math.floor(b.min.x/8),x1=Math.floor(b.max.x/8),z0=Math.floor(b.min.z/8),z1=Math.floor(b.max.z/8);entry.keys=[];if((x1-x0+1)*(z1-z0+1)>200){this.largeEntries.add(entry);return;}for(var x=x0;x<=x1;x++)for(var z=z0;z<=z1;z++){var key=x+','+z,cell=this.queryCells.get(key);if(!cell){cell=new Set();this.queryCells.set(key,cell);}cell.add(entry);entry.keys.push(key);}};
Geometry.prototype.unindexEntry=function(entry){this.largeEntries.delete(entry);for(var i=0;i<entry.keys.length;i++){var key=entry.keys[i],cell=this.queryCells.get(key);cell.delete(entry);if(!cell.size)this.queryCells.delete(key);}};
Geometry.prototype.queryEntries=function(p,radius){var seen=new Set(this.largeEntries),x0=Math.floor((p.x-radius)/8),x1=Math.floor((p.x+radius)/8),z0=Math.floor((p.z-radius)/8),z1=Math.floor((p.z+radius)/8);for(var x=x0;x<=x1;x++)for(var z=z0;z<=z1;z++){var cell=this.queryCells.get(x+','+z);if(cell)cell.forEach(function(e){seen.add(e);});}return Array.from(seen);};
Geometry.prototype.sync=function(){this.frame++;var roots=[],self=this;this.records.forEach(function(r){var root=r.o;while(root.parent)root=root.parent;if(roots.indexOf(root)<0){root.updateMatrixWorld(true);roots.push(root);}r.active=visible(r.o);var moved=!r.matrix.equals(r.o.matrixWorld),instancesChanged=r.o.isInstancedMesh&&(moved||!r.instances||r.version!==r.o.instanceMatrix.version);r.matrix.copy(r.o.matrixWorld);if(moved||!r.ready)r.inverse.copy(r.matrix).invert();if(instancesChanged){r.instances=[];for(var j=0;j<r.o.count;j++){r.o.getMatrixAt(j,im);var matrix=new T.Matrix4().multiplyMatrices(r.matrix,im);r.instances.push({matrix:matrix,inverse:matrix.clone().invert()});}r.version=r.o.instanceMatrix.version;}
 if(moved||instancesChanged||!r.ready){if(r.entries)r.entries.forEach(function(e){self.unindexEntry(e);});r.entries=[];if(!r.o.geometry.boundingBox)r.o.geometry.computeBoundingBox();r.box=r.box||new T.Box3();r.box.copy(r.o.geometry.boundingBox).applyMatrix4(r.matrix);if(r.instances){for(var bi=0;bi<r.instances.length;bi++){var ib=r.instances[bi];ib.box=new T.Box3().copy(r.o.geometry.boundingBox).applyMatrix4(ib.matrix);var entry={r:r,matrix:ib.matrix,inverse:ib.inverse,box:ib.box,instance:bi};r.entries.push(entry);self.indexEntry(entry);}}else {var entry={r:r,matrix:r.matrix,inverse:r.inverse,box:r.box,instance:-1};r.entries.push(entry);self.indexEntry(entry);}}r.ready=true;});};
Geometry.prototype.each=function(fn,entries){if(entries){for(var ei=0;ei<entries.length;ei++){var e=entries[ei];if(e.r.active&&fn(e.r,e.matrix,e.inverse,e.instance))return true;}return false;}for(var i=0;i<this.records.length;i++){var r=this.records[i];if(!r.active)continue;if(r.o.isInstancedMesh){for(var j=0;j<r.o.count;j++){var instance=r.instances[j];if(fn(r,instance.matrix,instance.inverse,j))return true;}}else if(fn(r,r.matrix,r.inverse,-1))return true;}return false;};
Geometry.prototype.nearest=function(point,limit){var best=limit||Infinity,result=null;this.each(function(r,m,mi,instance){var worldBox=instance<0?r.box:r.instances[instance].box;if(worldBox.distanceToPoint(point)>best)return false;local.copy(point).applyMatrix4(mi);var bvh=r.bvh;function visit(n){if(n.box.distanceToPoint(local)>best)return;if(n.ids){for(var k=0;k<n.ids.length;k++){triangle(bvh.g,n.ids[k]);tri.closestPointToPoint(local,hit);hit.applyMatrix4(m);var d=hit.distanceTo(point);if(d<best){best=d;result={distance:d,point:hit.clone(),object:r.o.name||r.o.uuid,instance:instance};}}}else{visit(n.left);visit(n.right);}}visit(bvh.root);return false;},limit?this.queryEntries(point,limit):null);return result;};
Geometry.prototype.raycast=function(origin,direction,maxDistance,opaque,support){var best=maxDistance||1000,result=null;worldRay.set(origin,direction);this.each(function(r,m,mi,instance){if(opaque&&!r.opaque)return false;var worldBox=instance<0?r.box:r.instances[instance].box;if(!support&&(!worldRay.intersectBox(worldBox,worldHit)||!worldBox.containsPoint(origin)&&worldHit.distanceTo(origin)>best))return false;if(support&&direction.x===0&&direction.z===0){var bb=instance<0?r.box:r.instances[instance].box;if(origin.x<bb.min.x||origin.x>bb.max.x||origin.z<bb.min.z||origin.z>bb.max.z||origin.y<bb.min.y||origin.y-best>bb.max.y)return false;}rr.origin.copy(origin).applyMatrix4(mi);rr.direction.copy(direction).transformDirection(mi);var bvh=r.bvh;function visit(n){if(!rr.intersectBox(n.box,hit))return;if(!n.box.containsPoint(rr.origin)&&hit.distanceTo(rr.origin)>best)return;if(n.ids){for(var k=0;k<n.ids.length;k++){triangle(bvh.g,n.ids[k]);if(support){tri.getNormal(Q);Q.transformDirection(m);if(Q.y<.55)continue;}if(rr.intersectTriangle(A,B,C,false,hit)){hit.applyMatrix4(m);var d=hit.distanceTo(origin);if(d<best){best=d;result={distance:d,y:hit.y,point:hit.clone(),object:r.o.name||r.o.uuid,instance:instance};if(opaque)return;}}}}else{visit(n.left);visit(n.right);}}visit(bvh.root);return opaque&&!!result;},support&&direction.x===0&&direction.z===0?this.queryEntries(origin,0):null);return result;};
Geometry.prototype.support=function(p,yaw,stride){var best=null,cy=Math.cos(yaw||0),sy=Math.sin(yaw||0);for(var side=-1;side<=1;side+=2)for(var f=-1;f<=1;f++){var x=side*.29,z=.09+side*(stride||0)/2+f*.33,q=new T.Vector3(p.x+x*cy+z*sy,p.y,p.z+z*cy-x*sy),g=this.ground(q);if(g&&(!best||Math.abs(g.y-p.y)<Math.abs(best.y-p.y)))best=g;}return best;};
Geometry.prototype.sole=function(p,yaw){var best=null,cy=Math.cos(yaw||0),sy=Math.sin(yaw||0);for(var f=-1;f<=1;f++){var z=f*.33,q=new T.Vector3(p.x+z*sy,p.y,p.z+z*cy),g=this.ground(q);if(g&&(!best||Math.abs(g.y-p.y)<Math.abs(best.y-p.y)))best=g;}return best;};
Geometry.prototype.ground=function(p){groundOrigin.set(p.x,p.y+.85,p.z);return this.raycast(groundOrigin,down,1.7,false,true);};
// Static broad phase is built once. Dynamic door boxes are queried from their current values.
function Spatial(list){this.list=list||[];this.cells=new Map();this.large=[];this.dynamic=[];var self=this;this.list.forEach(function(c){var b=box(c);if(!b.min||!b.max)return;if(c.dynamic){self.dynamic.push(c);return;}var pad=c.kind==='door'?3:0;var x0=Math.floor((b.min.x-pad)/8),x1=Math.floor((b.max.x+pad)/8),z0=Math.floor((b.min.z-pad)/8),z1=Math.floor((b.max.z+pad)/8),y0=Math.floor((b.min.y-4)/4),y1=Math.floor(b.max.y/4);if((x1-x0+1)*(z1-z0+1)*(y1-y0+1)>200){self.large.push(c);return;}for(var x=x0;x<=x1;x++)for(var y=y0;y<=y1;y++)for(var z=z0;z<=z1;z++){var k=x+','+y+','+z;if(!self.cells.has(k))self.cells.set(k,[]);self.cells.get(k).push(c);}});}
Spatial.prototype.query=function(p,r){var out=this.large.concat(this.dynamic),seen=new Set(out),x0=Math.floor((p.x-r)/8),x1=Math.floor((p.x+r)/8),z0=Math.floor((p.z-r)/8),z1=Math.floor((p.z+r)/8),y=Math.floor(p.y/4);for(var x=x0;x<=x1;x++)for(var z=z0;z<=z1;z++){var list=this.cells.get(x+','+y+','+z)||[];for(var j=0;j<list.length;j++)if(!seen.has(list[j])){seen.add(list[j]);out.push(list[j]);}}return out;};
function CollisionSet(sources){this.sources=sources;this.views=new Map();}
CollisionSet.prototype.query=function(p,r){var out=[],self=this;this.sources.forEach(function(source){var local=p.clone().sub(source.offset),list=source.index.query(local,r);for(var i=0;i<list.length;i++){var c=list[i],b=box(c);if(b.max.y<local.y+.01||b.min.y>local.y+4||b.min.x>local.x+r||b.max.x<local.x-r||b.min.z>local.z+r||b.max.z<local.z-r||!enabled(c))continue;var view=self.views.get(c);if(!view){view={id:c.id,kind:c.kind,owner:c.owner,supportId:c.supportId,type:c.type,box:new T.Box3()};self.views.set(c,view);}view.enabled=enabled(c);view.box.min.set(c.min.x+source.offset.x,c.min.y+source.offset.y,c.min.z+source.offset.z);view.box.max.set(c.max.x+source.offset.x,c.max.y+source.offset.y,c.max.z+source.offset.z);out.push(view);}});return out;};
function near(list,p,r){return list.query?list.query(p,r):list;}
function box(c){return c.box||c.bounds||c;}
function enabled(c){return c.enabled!==false&&c.active!==false&&(!c.isActive||c.isActive());}
function obstacle(c,p,r,h,supportId){if(!enabled(c))return false;var b=box(c);if(!b.min||!b.max)return false;if(c.kind==='floor'&&c.supportId&&c.supportId===supportId&&b.max.y<p.y+.65)return false;if(b.max.y<=p.y+.16||b.min.y>=p.y+h)return false;var dx=Math.max(b.min.x-p.x,0,p.x-b.max.x),dz=Math.max(b.min.z-p.z,0,p.z-b.max.z);return dx*dx+dz*dz<r*r;}
function clear(p,colliders,r,h,supportId){colliders=near(colliders,p,r);for(var i=0;i<colliders.length;i++)if(obstacle(colliders[i],p,r,h,supportId))return false;return true;}
function clamp(p,colliders,r,h,supportId){var q=p.clone(),source=colliders;for(var pass=0;pass<8;pass++){var changed=false;colliders=near(source,q,r);for(var i=0;i<colliders.length;i++){var c=colliders[i];if(!obstacle(c,q,r,h,supportId))continue;var b=box(c),nx=Math.max(b.min.x,Math.min(b.max.x,q.x)),nz=Math.max(b.min.z,Math.min(b.max.z,q.z)),dx=q.x-nx,dz=q.z-nz,d=Math.hypot(dx,dz);if(d>.0001){q.x+=dx/d*(r-d+.01);q.z+=dz/d*(r-d+.01);}else{var sides=[{d:q.x-b.min.x,a:'x',v:b.min.x-r-.01},{d:b.max.x-q.x,a:'x',v:b.max.x+r+.01},{d:q.z-b.min.z,a:'z',v:b.min.z-r-.01},{d:b.max.z-q.z,a:'z',v:b.max.z+r+.01}];sides.sort(function(a,b){return a.d-b.d;});q[sides[0].a]=sides[0].v;}changed=true;}if(!changed)break;}return q;}

// Gameplay broad phase: compiled once from the public collider contract. No triangles.
// Each padded cell owns a deduplicated candidate list, so lookup allocates nothing.
function Field(list,escalators){
 this.cells=new Map();this.floorCells=new Map();this.large=[];this.largeFloors=[];this.dynamic=[];this.dynamicRows=new Map();this.bodyCells=new Map();this.bodyLarge=[];this.dynamicCells=new Map();this.escalators=escalators||[];this.groundResult={y:0,id:'',kind:'floor'};var self=this;
 (list||[]).forEach(function(c){var b=box(c);if(!b.min||!b.max)return;if(c.dynamic){if(c.motion&&c.motion.axis==='x'){for(var ry=Math.floor((b.min.y-4.2)/4);ry<=Math.floor((b.max.y+1)/4);ry++)for(var rz=Math.floor((b.min.z-3.6)/8);rz<=Math.floor((b.max.z+3.6)/8);rz++){var rk=(ry+128)*1024+rz+512,row=self.dynamicRows.get(rk);if(!row){row=[];self.dynamicRows.set(rk,row);}row.push(c);}}else self.dynamic.push(c);return;}
 var x0=Math.floor((b.min.x-3.6)/8),x1=Math.floor((b.max.x+3.6)/8),z0=Math.floor((b.min.z-3.6)/8),z1=Math.floor((b.max.z+3.6)/8),y0=Math.floor((b.min.y-4.2)/4),y1=Math.floor((b.max.y+1)/4);
 if((x1-x0+1)*(z1-z0+1)*(y1-y0+1)>1800){self.large.push(c);return;}
 for(var x=x0;x<=x1;x++)for(var y=y0;y<=y1;y++)for(var z=z0;z<=z1;z++){var key=(x+256)*1048576+(y+128)*1024+z+512,cell=self.cells.get(key);if(!cell){cell=[];self.cells.set(key,cell);}cell.push(c);}
 });
 (list||[]).forEach(function(c){if(c.kind!=='floor'||c.supportId||c.dynamic)return;var b=box(c),x0=Math.floor(b.min.x/8),x1=Math.floor(b.max.x/8),z0=Math.floor(b.min.z/8),z1=Math.floor(b.max.z/8),y0=Math.floor((b.max.y-.85)/4),y1=Math.floor((b.max.y+.85)/4);if((x1-x0+1)*(z1-z0+1)*(y1-y0+1)>1800){self.largeFloors.push(c);return;}for(var x=x0;x<=x1;x++)for(var y=y0;y<=y1;y++)for(var z=z0;z<=z1;z++){var key=(x+256)*1048576+(y+128)*1024+z+512,floors=self.floorCells.get(key);if(!floors){floors=[];self.floorCells.set(key,floors);}floors.push(c);}});
 (list||[]).forEach(function(c){if(c.dynamic&&c.motion&&c.motion.axis==='x')return;var b=box(c),pad=c.dynamic?6:1.9,x0=Math.floor((b.min.x-pad)/8),x1=Math.floor((b.max.x+pad)/8),z0=Math.floor((b.min.z-pad)/8),z1=Math.floor((b.max.z+pad)/8),y0=Math.floor(b.min.y-4.2),y1=Math.floor(b.max.y+1),target=c.dynamic?self.dynamicCells:self.bodyCells;if(!c.dynamic&&(x1-x0+1)*(z1-z0+1)*(y1-y0+1)>1800){self.bodyLarge.push(c);return;}for(var x=x0;x<=x1;x++)for(var y=y0;y<=y1;y++)for(var z=z0;z<=z1;z++){if(!c.dynamic&&c.kind==='floor'&&b.max.y<=y+.65)continue;var key=(x+256)*1048576+(y+128)*1024+z+512,cell=target.get(key);if(!cell){cell=[];target.set(key,cell);}cell.push(c);}});
 this.empty=[];
}
Field.prototype.bodyAt=function(x,y,z){return this.bodyCells.get((Math.floor(x/8)+256)*1048576+(Math.floor(y)+128)*1024+Math.floor(z/8)+512)||this.empty;};
Field.prototype.doorAt=function(x,y,z){return this.dynamicCells.get((Math.floor(x/8)+256)*1048576+(Math.floor(y)+128)*1024+Math.floor(z/8)+512)||this.empty;};
Field.prototype.flatAround=function(x,y,z,r){var list=this.at(x,y,z);for(var set=0;set<2;set++){if(set)list=this.large;for(var i=0;i<list.length;i++){var c=list[i];if(c.kind!=='floor'||c.supportId||!enabled(c))continue;var b=box(c);if(Math.abs(b.max.y-y)>.85||Math.abs(b.max.y-y)<.01)continue;if(b.min.x<x+r&&b.max.x>x-r&&b.min.z<z+r&&b.max.z>z-r)return false;}}return true;};
Field.prototype.at=function(x,y,z){return this.cells.get((Math.floor(x/8)+256)*1048576+(Math.floor(y/4)+128)*1024+Math.floor(z/8)+512)||this.empty;};
Field.prototype.dynamicAt=function(y,z){return this.dynamicRows.get((Math.floor(y/4)+128)*1024+Math.floor(z/8)+512)||this.empty;};
Field.prototype.ground=function(x,y,z){
 for(var ei=0;ei<this.escalators.length;ei++){var e=this.escalators[ei];if(e.enabled===false||x<Math.min(e.top.x,e.bottom.x)-.9||x>Math.max(e.top.x,e.bottom.x)+.9||Math.abs(z-e.top.z)>e.width*.5+.01)continue;var g=(e.sampleFast||e.sample).call(e,x,z,y);if(g)return g;}
 var best=-Infinity,id='',list=this.floorCells.get((Math.floor(x/8)+256)*1048576+(Math.floor(y/4)+128)*1024+Math.floor(z/8)+512)||this.empty;for(var si=0;si<2;si++){if(si)list=this.largeFloors;for(var i=0;i<list.length;i++){var c=list[i];if(c.kind!=='floor'||c.supportId||!enabled(c))continue;var b=box(c);if(x>=b.min.x-.0001&&x<=b.max.x+.0001&&z>=b.min.z-.0001&&z<=b.max.z+.0001&&b.max.y>=y-.85&&b.max.y<=y+.85&&b.max.y>best){best=b.max.y;id=c.id;}}}
 if(!isFinite(best))return null;var out=this.groundResult;out.y=best;out.id=id;out.kind='floor';return out;
};
function Runtime(station,train){this.station=station;this.train=train;this.stationField=new Field(station.colliders,station.escalators);this.trainField=new Field(train.colliders);this.local=new T.Vector3();this.result={y:0,id:'',kind:'floor'};this.list=[];this.views=new Map();this.zero=new T.Vector3();this.nearResult={distance:0,point:new T.Vector3(),object:''};this._point=new T.Vector3();this.attached=false;}
Runtime.prototype.ground=function(p,trainLocal){
 var out=this.result,g,offset;if(trainLocal){g=this.trainField.ground(p.x,p.y,p.z);if(!g)return null;out.y=g.y;out.id=g.id;out.kind=g.kind;return out;}
 var found=false,best=Infinity;if(this.station.group.visible){offset=this.station.group.position;g=this.stationField.ground(p.x-offset.x,p.y-offset.y,p.z-offset.z);if(g){out.y=g.y+offset.y;out.id=g.id;out.kind=g.kind;best=Math.abs(out.y-p.y);found=true;}}
 offset=this.train.group.position;if(this.train.group.visible&&Math.abs(p.z-offset.z)<5.25&&Math.abs(p.x-offset.x)<126&&p.y<offset.y+11){g=this.trainField.ground(p.x-offset.x,p.y-offset.y,p.z-offset.z);if(g&&Math.abs(g.y+offset.y-p.y)<best){out.y=g.y+offset.y;out.id=g.id;out.kind=g.kind;found=true;}}return found?out:null;
};
Runtime.prototype.walkable=function(p,margin){var offset=this.station.group.position,x=p.x-offset.x,y=p.y-offset.y,z=p.z-offset.z,regions=this.station.walkableRegions||[];for(var i=0;i<regions.length;i++){var r=regions[i];if(r.enabled===false||Math.abs(r.y-y)>.85||x<r.minX+margin||x>r.maxX-margin||z<r.minZ+margin||z>r.maxZ-margin)continue;var holes=r.holes||[],okay=true;for(var j=0;j<holes.length;j++){var h=holes[j];if(x>h[0]-margin&&x<h[1]+margin&&z>h[2]-margin&&z<h[3]+margin){okay=false;break;}}if(okay)return true;}return false;};
Runtime.prototype.query=function(p,r){var out=this.list;out.length=0;var self=this,base=this.attached?this.train.group.position:this.zero;function collect(field,offset){var x=p.x+base.x-offset.x,y=p.y+base.y-offset.y,z=p.z+base.z-offset.z,sets=[field.at(x,y,z),field.large,field.dynamicAt(y,z),field.dynamic];for(var si=0;si<4;si++)for(var i=0;i<sets[si].length;i++){var c=sets[si][i],b=box(c);if(!enabled(c)||b.max.y<y-.9||b.min.y>y+4.2||b.min.x>x+r||b.max.x<x-r||b.min.z>z+r||b.max.z<z-r)continue;var v=self.views.get(c);if(!v){v={id:c.id,kind:c.kind,owner:c.owner,supportId:c.supportId,type:c.type,box:new T.Box3()};self.views.set(c,v);}v.enabled=true;v.box.min.set(b.min.x+offset.x-base.x,b.min.y+offset.y-base.y,b.min.z+offset.z-base.z);v.box.max.set(b.max.x+offset.x-base.x,b.max.y+offset.y-base.y,b.max.z+offset.z-base.z);out.push(v);}}
 if(this.station.group.visible)collect(this.stationField,this.station.group.position);if(this.train.group.visible)collect(this.trainField,this.train.group.position);return out;};
Runtime.prototype.nearest=function(p,limit){var old=this.attached;this.attached=false;var list=this.query(p,limit),best=limit,out=null;for(var i=0;i<list.length;i++){var b=box(list[i]),qx=Math.max(b.min.x,Math.min(b.max.x,p.x)),qy=Math.max(b.min.y,Math.min(b.max.y,p.y)),qz=Math.max(b.min.z,Math.min(b.max.z,p.z)),d=Math.hypot(p.x-qx,p.y-qy,p.z-qz);if(d<best){best=d;this.nearResult.distance=d;this.nearResult.point.set(qx,qy,qz);this.nearResult.object=list[i].id;out=this.nearResult;}}this.attached=old;return out;};
Runtime.prototype.support=function(p,yaw,stride){var cy=Math.cos(yaw||0),sy=Math.sin(yaw||0),best=Infinity,out=null,saved={y:0,id:'',kind:'floor'};for(var side=-1;side<=1;side+=2)for(var f=-1;f<=1;f++){var x=side*.29,z=.09+side*(stride||0)/2+f*.33;this._point.set(p.x+x*cy+z*sy,p.y,p.z+z*cy-x*sy);var g=this.ground(this._point);if(g&&Math.abs(g.y-p.y)<best){best=Math.abs(g.y-p.y);saved.y=g.y;saved.id=g.id;saved.kind=g.kind;out=saved;}}return out;};
Runtime.prototype.sole=function(p,yaw){return this.support(p,yaw,0);};

var dirs=[];for(var x=-1;x<=1;x++)for(var y=-1;y<=1;y++)for(var z=-1;z<=1;z++)if(x||y||z)dirs.push(new T.Vector3(x,y,z).normalize());
function npcRadius(a){return (a.pose==='phone'?1.7:1.4)*a.scale;}
function Audit(context){this.context=context;this.reset();}
Audit.prototype.reset=function(){this.counts={cameraGeometry:0,undergroundOpenRay:0,npcPersonalSpace:0,npcOverlap:0,npcStaticCollider:0,npcUnsupportedFeet:0,npcInteractionObstruction:0,unsupportedFeet:0,trainPlatformIntersection:0,missingContract:0};this.examples=[];this.examplesByType={};this.frames=0;this.byStage={};this.minima={cameraClearance:Infinity,npcPlayer:Infinity,npcPair:Infinity};this.seconds=0;};
Audit.prototype.add=function(type,c,p,object,amount){this.counts[type]++;var key=c.stage+'|'+type;this.byStage[key]=(this.byStage[key]||0)+1;var item={type:type,stage:c.stage,position:{x:p.x,y:p.y,z:p.z},objects:object,amount:amount,frame:this.frames};if(type==='undergroundOpenRay'){item.feet={x:c.feet.x,y:c.feet.y,z:c.feet.z};item.view={yaw:c.camera.rotation.y,pitch:c.camera.rotation.x};}if(!this.examplesByType[type])this.examplesByType[type]=[];var examples=this.examplesByType[type];examples.push(item);examples.sort(function(a,b){return b.amount-a.amount;});if(examples.length>8)examples.length=8;this.examples.push(item);this.examples.sort(function(a,b){return b.amount-a.amount;});if(this.examples.length>32)this.examples.length=32;};
Audit.prototype.update=function(dt){var c=this.context();if(!c.active)return;this.frames++;this.seconds+=dt;var geo=c.geometry,p=c.camera.position,nearest=geo.nearest(p,8);if(nearest){this.minima.cameraClearance=Math.min(this.minima.cameraClearance,nearest.distance);if(nearest.distance<.999)this.add('cameraGeometry',c,p,[nearest.object],1-nearest.distance);}if(!c.station.colliders||!c.train.colliders||!GZ.Station.validate)this.add('missingContract',c,p,['WORLD_API colliders / validate'],1);
 if(c.feet.y<27.9){for(var i=0;i<dirs.length;i++)if(!geo.raycast(p,dirs[i],850,true,false))this.add('undergroundOpenRay',c,p,['direction '+dirs[i].toArray().join(',')],1);c.camera.updateMatrixWorld(true);var viewPoints=[[0,0],[-1,-1],[-1,1],[1,-1],[1,1]];for(i=0;i<viewPoints.length;i++){var direction=new T.Vector3(viewPoints[i][0],viewPoints[i][1],.5).unproject(c.camera).sub(p).normalize();if(!geo.raycast(p,direction,850,true,false))this.add('undergroundOpenRay',c,p,['visible-view '+viewPoints[i].join(',')],1);}}
 var as=c.crowd.actors,offset=c.crowd.group.parent===c.train.group?c.train.group.position:new T.Vector3();for(i=0;i<as.length;i++){var a=as[i];if(!a.visible)continue;var ap=a.position.clone().add(offset),height=3.85*a.scale,vertical=Math.abs(ap.y-c.feet.y);if(vertical<3.85){var distance=Math.hypot(ap.x-c.feet.x,ap.z-c.feet.z);this.minima.npcPlayer=Math.min(this.minima.npcPlayer,distance);if(distance<3.499)this.add('npcPersonalSpace',c,ap,['npc-'+i],3.5-distance);}
 for(var j=i+1;j<as.length;j++){var b=as[j];if(!b.visible||Math.abs(a.position.y-b.position.y)>Math.max(height,3.85*b.scale))continue;var dist=Math.hypot(a.position.x-b.position.x,a.position.z-b.position.z),minimum=npcRadius(a)+npcRadius(b);this.minima.npcPair=Math.min(this.minima.npcPair,dist);if(dist<minimum-.001)this.add('npcOverlap',c,ap,['npc-'+i,'npc-'+j],minimum-dist);}
 var contact=c.crowd.footContact(a);if(!contact.supported)this.add('npcUnsupportedFeet',c,ap,['npc-'+i,JSON.stringify(contact.details)],isFinite(contact.gap)?contact.gap:2);
 var bodyHit=c.crowd.staticHit(a,a.position);if(bodyHit)this.add('npcStaticCollider',c,ap,['npc-'+i,bodyHit.collider.id||bodyHit.collider.owner,bodyHit.part],1);}

 if(c.interaction){var blocking=c.crowd.blocksInteraction(c.camera.position,c.interaction.point);if(blocking)this.add('npcInteractionObstruction',c,blocking.position,['npc-'+blocking.id,blocking.part,c.interaction.kind],1);}
 var ground=geo.support(c.feet,c.bodyYaw,c.moving?1.2:0);if(!ground||Math.abs(ground.y-c.feet.y)>.16)this.add('unsupportedFeet',c,c.feet,[ground?ground.object:'no supporting triangle'],ground?Math.abs(ground.y-c.feet.y):2);
 if(c.station.group.visible&&c.train.group.visible&&GZ.Station.validateTrainClearance){var check=GZ.Station.validateTrainClearance(c.station,c.train);if(!check.ok)this.add('trainPlatformIntersection',c,c.train.group.position,check.objects||['train','platform/PSD'],check.penetration||1);}else if(c.station.group.visible&&c.train.group.visible){var sc=c.station.colliders||[],bounds=c.train.bodyBounds||new T.Box3(new T.Vector3(-c.train.length/2,0,-5),new T.Vector3(c.train.length/2,10,5));var tb=new T.Box3(bounds.min.clone().add(c.train.group.position),bounds.max.clone().add(c.train.group.position));for(i=0;i<sc.length;i++){var b=box(sc[i]);if((/站台|屏蔽门/.test(sc[i].owner||''))&&enabled(sc[i])&&b.min&&b.max&&tb.intersectsBox(b))this.add('trainPlatformIntersection',c,c.train.group.position,['train',sc[i].id||sc[i].name||i],1);}}
};
Audit.prototype.report=function(){return {frames:this.frames,seconds:this.seconds,counts:Object.assign({},this.counts),total:Object.values(this.counts).reduce(function(a,b){return a+b;},0),worst:this.examples.slice(),worstByType:this.examplesByType,byStage:Object.assign({},this.byStage),minima:this.minima,method:'Every rendered journey frame: exact triangle BVH camera distance, 26 sphere directions + center/four corners of the actual view, opaque geometry rays, exact support triangle; conservative body spacing, all 19 articulated part bounds against real colliders, rendered two-shoe soles/stride and train AABB.'};};
GZ.PlayPhysics={Runtime:Runtime,Field:Field,Geometry:Geometry,Audit:Audit,Spatial:Spatial,CollisionSet:CollisionSet,box:box,enabled:enabled,npcRadius:npcRadius,obstacle:obstacle,clear:clear,clamp:clamp,directions:dirs};
})();
